apiVersion : apps/v1
kind: Deployment
metadata:
  name: "diaggarw-48a0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "diaggarw-48a0"
  template:
    metadata:
      labels:
        app: "diaggarw-48a0"
    spec:
      containers:
        - name: "diaggarw-48a0"
          image: "divman.azurecr.io/diaggarw48a0"
          ports:
          - containerPort: 8080