apiVersion : apps/v1
kind: Deployment
metadata:
  name: "divman-d455"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "divman-d455"
  template:
    metadata:
      labels:
        app: "divman-d455"
    spec:
      containers:
        - name: "divman-d455"
          image: "divman.azurecr.io/divmand455"
          ports:
          - containerPort: 8080