apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: diaggarw
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: diaggarw
    spec:
      containers:
        - name: diaggarw
          image: ddivanshu.azurecr.io/diaggarw
          ports:
          - containerPort: 80