apiVersion : apps/v1
kind: Deployment
metadata:
  name: "diaggarw-e29c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "diaggarw-e29c"
  template:
    metadata:
      labels:
        app: "diaggarw-e29c"
    spec:
      containers:
        - name: "diaggarw-e29c"
          image: "diaggarwacr000.azurecr.io/diaggarw4ef3"
          ports:
          - containerPort: 