apiVersion : apps/v1
kind: Deployment
metadata:
  name: "diaggarw-d9f7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "diaggarw-d9f7"
  template:
    metadata:
      labels:
        app: "diaggarw-d9f7"
    spec:
      containers:
        - name: "diaggarw-d9f7"
          image: "ddivanshu.azurecr.io/diaggarw81b0"
          ports:
          - containerPort: 