apiVersion : apps/v1
kind: Deployment
metadata:
  name: "diaggarw-09e6"
spec:
  selector:
    matchLabels: "diaggarw-09e6"
      app: ""
  replicas: 2
  template:
    metadata:
      labels:
        app: "diaggarw-09e6"
    spec:
      containers:
        - name: "diaggarw-09e6"
          image: "diaggarwregistry.azurecr.io/diaggarw4521"
          ports:
          - containerPort: 80
