apiVersion : apps/v1
kind: Deployment
metadata:
  name: "diaggarw-8140"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "diaggarw-8140"
  template:
    metadata:
      labels:
        app: "diaggarw-8140"
    spec:
      containers:
        - name: "diaggarw-8140"
          image: "diaggarwacr111.azurecr.io/diaggarwf91b"
          ports:
          - containerPort: 