apiVersion : apps/v1
kind: Deployment
metadata:
  name: "divman-b9b9"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "divman-b9b9"
  template:
    metadata:
      labels:
        app: "divman-b9b9"
    spec:
      containers:
        - name: "divman-b9b9"
          image: "divman.azurecr.io/divmanb9b9"
          ports:
          - containerPort: 8080