apiVersion: v1
kind: Service
metadata:
    name: "diaggarw-8140"
    labels:
        app: "diaggarw-8140"
spec:
    type: LoadBalancer
    ports:
    - port: 
      targetPort: 
      protocol: TCP
      name: http
    selector:
        app: "diaggarw-8140"