apiVersion: v1
kind: Service
metadata:
    name: "diaggarwtest-2d58"
    labels:
        app: "diaggarwtest-2d58"
spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "diaggarwtest-2d58"
