apiVersion: v1
kind: Service
metadata:
    name: "divman-b9b9"
    labels:
        app: "divman-b9b9"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "divman-b9b9"