apiVersion: v1
kind: Service
metadata:
    name: "diaggarwaks-f293"
    labels:
        app: "diaggarwaks-f293"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "diaggarwaks-f293"