apiVersion: v1
kind: Service
metadata:
    name: "diaggarw-453e"
    labels:
        app: "diaggarw-453e"
spec:
    type: LoadBalancer
    ports:
    - port: 
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "diaggarw-453e"