apiVersion: v1
kind: Service
metadata:
    name: "diaggarw-1337"
    labels:
        app: "diaggarw-1337"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "diaggarw-1337"