on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n diaggarwt -g diaggarwt850e-rg --location "South India" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n diaggarwt --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n diaggarwt --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n diaggarwt --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: diaggarwt.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t diaggarwt.azurecr.io/diaggarwtest:${{ github.sha }}
        docker push diaggarwt.azurecr.io/diaggarwtest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_diaggarwtest_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep diaggarwtest6319 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace diaggarwtest6319`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: diaggarwtest6319
        container-registry-url: diaggarwt.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: diaggarwtestdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: diaggarwtest6319
        manifests: |
          manifests/deployment-16.yml
          manifests/service-16.yml
        images: |
          diaggarwt.azurecr.io/diaggarwtest:${{ github.sha }}
        imagepullsecrets: |
          diaggarwtestdockerauth