on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_GITHUB_SECRET}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n diaggarwacr111 -g diaggarwacr111a96d-rg --location "South Central US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n diaggarwacr111 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n diaggarwacr111 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n diaggarwacr111 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: diaggarwacr111.azurecr.io
        username: ${{steps.create-acr.outputs.acr_username}}
        password: ${{steps.create-acr.outputs.acr_password}}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t diaggarwacr111.azurecr.io/diaggarwf91b:${{github.sha}}
        docker push diaggarwacr111.azurecr.io/diaggarwf91b:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_diaggarw_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep diaggarw7886 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace diaggarw7886`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: diaggarw7886
        container-registry-url: diaggarwacr111.azurecr.io
        container-registry-username: ${{steps.create-acr.outputs.acr_username}}
        container-registry-password: ${{steps.create-acr.outputs.acr_password}}
        secret-name: diaggarwdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: diaggarw7886
        manifests: |
          manifests/deployment-42f8.yml
          manifests/service-42f8.yml
        images: |
          diaggarwacr111.azurecr.io/diaggarwf91b:${{github.sha}}
        imagepullsecrets: |
          diaggarwdockerauth